name: Test CI Setup

on:
  workflow_dispatch:  # Allows manual triggering for testing

jobs:
  test-ci-setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv

    - name: Install Python dependencies
      run: |
        pipenv install --dev --python $(which python)

    - name: Install Node.js dependencies
      run: |
        npm install

    - name: Validate CI setup
      run: |
        npm run validate-ci
      env:
        CI: true

    - name: Run comprehensive tests
      run: |
        npm run test:all
      env:
        CI: true
